# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47c90ddfdd4f4e8d0386e81d5afb5fff833823c2222c2e53dd51c2c9d94584023f318ef7fb4732da29ed7ee5c72e1de2e338f843315522d34fae7ffc18fdda83

test:
  secret_key_base: aa26fe7bcbceb1bc4c683ae090642ac9c5ef861416752c3f361518b21965d438258e0b23acbb6b5dcc2faa49fdd783daac7fef1ea2bcdb1816ed0e1b9e204bb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
